import { formatBytes, formatSavingsPct } from "./format";
import type { ManifestVariant } from "./api";

export interface AppRefs {
  dropzone: HTMLDivElement;
  fileInput: HTMLInputElement;
  statusEl: HTMLParagraphElement;
  resultsSection: HTMLElement;
  resultsBody: HTMLTableSectionElement;
}

export function mountApp(root: HTMLElement): AppRefs {
  root.innerHTML = `
    <main class="app">
      <header class="app__header">
        <h1>Image Optimizer</h1>
        <p class="app__tagline">
          Drop an image — get WebP/AVIF variants back in seconds, generated by a live AWS pipeline
          (S3 → Lambda → S3 → CloudFront), not a canned demo.
        </p>
      </header>

      <div
        id="dropzone"
        class="dropzone"
        role="button"
        tabindex="0"
        aria-label="Drop an image here, or press Enter to choose a file"
      >
        <p>Drag an image here, or click to choose a file</p>
        <p class="dropzone__hint">JPEG, PNG, or WebP — up to 10 MB</p>
        <input
          id="file-input"
          type="file"
          accept="image/jpeg,image/png,image/webp"
          class="visually-hidden"
          aria-label="Choose an image file"
        />
      </div>

      <p id="status" class="status" role="status" aria-live="polite">Waiting for an image.</p>

      <section id="results" class="results" hidden>
        <div class="results__scroll">
          <table>
            <caption>Generated variants</caption>
            <thead>
              <tr>
                <th scope="col">Variant</th>
                <th scope="col">Original</th>
                <th scope="col">Optimized</th>
                <th scope="col">Savings</th>
                <th scope="col">Download</th>
              </tr>
            </thead>
            <tbody id="results-body"></tbody>
          </table>
        </div>
      </section>

      <footer class="app__footer">
        <p>
          Files self-destruct automatically after 60 minutes. No personal data is stored — nothing
          survives past your session.
        </p>
      </footer>
    </main>
  `;

  return {
    dropzone: root.querySelector<HTMLDivElement>("#dropzone")!,
    fileInput: root.querySelector<HTMLInputElement>("#file-input")!,
    statusEl: root.querySelector<HTMLParagraphElement>("#status")!,
    resultsSection: root.querySelector<HTMLElement>("#results")!,
    resultsBody: root.querySelector<HTMLTableSectionElement>("#results-body")!,
  };
}

export function setStatus(statusEl: HTMLElement, message: string): void {
  statusEl.textContent = message;
}

export function clearResults(refs: Pick<AppRefs, "resultsSection" | "resultsBody">): void {
  refs.resultsSection.hidden = true;
  refs.resultsBody.innerHTML = "";
}

export function renderResults(
  refs: Pick<AppRefs, "resultsSection" | "resultsBody">,
  originalBytes: number,
  variants: ManifestVariant[],
): void {
  refs.resultsSection.hidden = false;
  refs.resultsBody.innerHTML = variants
    .map((variant) => {
      const label = `${variant.width}×${variant.height} · ${variant.format.toUpperCase()}`;
      return `
        <tr>
          <td>${label}</td>
          <td>${formatBytes(originalBytes)}</td>
          <td>${formatBytes(variant.bytes)}</td>
          <td>${formatSavingsPct(variant.savingsPct)}</td>
          <td><a href="${variant.url}" target="_blank" rel="noopener">Download</a></td>
        </tr>
      `;
    })
    .join("");
}
